from typing import Protocol


class AuthRepository(Protocol):
    def init_schema(self) -> None: ...
    def is_authorized(self, channel: str, channel_id: str) -> str | None: ...
    def create_user(self, display_name: str) -> str: ...
    def link_identity(self, user_id: str, channel: str, channel_id: str) -> None: ...
    def create_invite(
        self,
        display_name: str,
        created_by: str,
        channel: str | None = None,
        channel_id: str | None = None,
    ) -> str: ...
    def redeem_invite(
        self, token: str, channel: str, channel_id: str
    ) -> tuple[str, str] | None: ...
    def revoke(self, channel: str, channel_id: str) -> bool: ...
    def list_identities(self) -> list[dict]: ...
    def has_any_user(self) -> bool: ...
    def bootstrap_admin(
        self, display_name: str, channel: str, channel_id: str
    ) -> str: ...
